# Generated by Django 4.2.6 on 2023-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tech', '0003_remove_post_profile_image_remove_post_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
