# Generated by Django 4.2.6 on 2023-10-22 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tech', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
