# Generated by Django 4.2.6 on 2023-10-22 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tech', '0007_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
    ]
